// 维护网址时只需编辑这个文件。category 和 color 用来控制分类及卡片强调色。
window.BOOKMARKS = [
  {
    title: "GitHub",
    url: "https://github.com/",
    description: "代码托管、协作开发与开源项目社区。",
    category: "开发",
    tags: ["代码", "开源", "Git"],
    color: "#24292f",
  },
  {
    title: "MDN Web Docs",
    url: "https://developer.mozilla.org/zh-CN/",
    description: "权威、完整的 Web 开发技术文档。",
    category: "开发",
    tags: ["前端", "文档", "Web"],
    color: "#8055b8",
  },
  {
    title: "Stack Overflow",
    url: "https://stackoverflow.com/",
    description: "面向程序员的技术问答与知识社区。",
    category: "开发",
    tags: ["问答", "编程"],
    color: "#e06c24",
  },
  {
    title: "ChatGPT",
    url: "https://chatgpt.com/",
    description: "用于写作、分析、学习与创意工作的 AI 助手。",
    category: "AI 工具",
    tags: ["AI", "效率", "写作"],
    color: "#10a37f",
  },
  {
    title: "Hugging Face",
    url: "https://huggingface.co/",
    description: "机器学习模型、数据集与应用的开放社区。",
    category: "AI 工具",
    tags: ["模型", "机器学习", "数据集"],
    color: "#d29922",
  },
  {
    title: "Figma",
    url: "https://www.figma.com/",
    description: "产品设计、原型制作与团队协作平台。",
    category: "设计",
    tags: ["UI", "原型", "协作"],
    color: "#a259ff",
  },
  {
    title: "Dribbble",
    url: "https://dribbble.com/",
    description: "浏览设计作品，发现视觉与交互灵感。",
    category: "设计",
    tags: ["灵感", "视觉", "作品"],
    color: "#ea4c89",
  },
  {
    title: "Notion",
    url: "https://www.notion.so/",
    description: "整合笔记、文档、项目和知识库的工作空间。",
    category: "效率",
    tags: ["笔记", "知识库", "协作"],
    color: "#4d5558",
  },
  {
    title: "Excalidraw",
    url: "https://excalidraw.com/",
    description: "快速绘制具有手绘风格的流程图和草图。",
    category: "效率",
    tags: ["绘图", "白板", "流程图"],
    color: "#6965db",
  },
  {
    title: "少数派",
    url: "https://sspai.com/",
    description: "高效工作、品质生活与数字工具内容社区。",
    category: "阅读",
    tags: ["效率", "数字生活", "文章"],
    color: "#d71920",
  },
  {
    title: "Wikipedia",
    url: "https://zh.wikipedia.org/",
    description: "自由、开放且持续更新的在线百科全书。",
    category: "阅读",
    tags: ["百科", "知识", "查询"],
    color: "#5b6468",
  },
  {
    title: "Internet Archive",
    url: "https://archive.org/",
    description: "保存网页、书籍、音视频与软件的数字档案馆。",
    category: "资源",
    tags: ["存档", "电子书", "历史"],
    color: "#8a6d3b",
  },
];
